/**
 * Enterprise Regulatory Filing System - Jurisdiction Configuration
 * Supports 50+ jurisdictions across Caribbean, Latin America, Europe, North America, Asia-Pacific, and Africa
 */

export interface FilingRequirement {
  id: string;
  type: 'QUARTERLY' | 'ANNUAL' | 'SEMI_ANNUAL' | 'MONTHLY' | 'ADHOC';
  name: string;
  description: string;
  dueDay: number; // Day of month or quarter end
  dueMonth?: number; // For annual filings
  graceDays: number;
  dataFormat: 'XML' | 'JSON' | 'CSV' | 'PDF' | 'XBRL';
  templateId?: string;
  requiredFields: string[];
  validationRules: ValidationRule[];
  penaltyAmount?: number;
  penaltyCurrency?: string;
}

export interface ValidationRule {
  id: string;
  field: string;
  rule: 'REQUIRED' | 'MIN_VALUE' | 'MAX_VALUE' | 'FORMAT' | 'RANGE' | 'CUSTOM';
  value?: string | number;
  message: string;
}

export interface JurisdictionConfig {
  code: string;
  name: string;
  region: string;
  regulator: {
    name: string;
    shortName: string;
    website: string;
    email: string;
    phone: string;
    address: string;
  };
  currency: string;
  timezone: string;
  filingRequirements: FilingRequirement[];
  capitalRequirements: {
    minimumCapital: number;
    solvencyMarginPercent: number;
    capitalAdequacyRatio: number;
  };
  investmentLimits: {
    maxEquityPercent: number;
    maxSingleIssuerPercent: number;
    maxPropertyPercent: number;
    maxForeignInvestmentPercent: number;
    restrictedAssets: string[];
  };
  governanceRequirements: {
    minBoardMembers: number;
    independentDirectorsPercent: number;
    auditCommitteeRequired: boolean;
    riskCommitteeRequired: boolean;
    actuaryRequired: boolean;
    complianceOfficerRequired: boolean;
  };
  dataFormatPreferences: ('XML' | 'JSON' | 'CSV' | 'PDF' | 'XBRL')[];
  electronicSubmissionEnabled: boolean;
  digitalSignatureRequired: boolean;
  reportingBasis: 'STATUTORY' | 'GAAP' | 'IFRS' | 'LOCAL';
}

// ============================================================================
// CARIBBEAN JURISDICTIONS
// ============================================================================

export const CARIBBEAN_JURISDICTIONS: JurisdictionConfig[] = [
  {
    code: 'TT',
    name: 'Trinidad & Tobago',
    region: 'Caribbean',
    regulator: {
      name: 'Central Bank of Trinidad and Tobago',
      shortName: 'CBTT',
      website: 'https://www.central-bank.org.tt',
      email: 'insurance@central-bank.org.tt',
      phone: '+1-868-621-3777',
      address: 'Eric Williams Financial Complex, Independence Square, Port of Spain',
    },
    currency: 'TTD',
    timezone: 'America/Port_of_Spain',
    filingRequirements: [
      {
        id: 'TT-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Insurance Return',
        description: 'Comprehensive quarterly return including premium income, claims, and reserves',
        dueDay: 30,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['grossPremiums', 'netPremiums', 'claimsPaid', 'claimsOutstanding', 'technicalReserves', 'solvencyMargin'],
        validationRules: [
          { id: 'TT-QR-V01', field: 'grossPremiums', rule: 'REQUIRED', message: 'Gross premiums is required' },
          { id: 'TT-QR-V02', field: 'technicalReserves', rule: 'MIN_VALUE', value: 0, message: 'Technical reserves must be positive' },
          { id: 'TT-QR-V03', field: 'solvencyMargin', rule: 'MIN_VALUE', value: 150, message: 'Solvency margin must be at least 150%' },
        ],
        penaltyAmount: 10000,
        penaltyCurrency: 'TTD',
      },
      {
        id: 'TT-AR-001',
        type: 'ANNUAL',
        name: 'Annual Financial Statements',
        description: 'Audited annual financial statements with actuarial certification',
        dueDay: 30,
        dueMonth: 6,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['balanceSheet', 'incomeStatement', 'cashFlow', 'actuarialReport', 'auditorsReport'],
        validationRules: [
          { id: 'TT-AR-V01', field: 'auditorsReport', rule: 'REQUIRED', message: 'Auditor\'s report is required' },
          { id: 'TT-AR-V02', field: 'actuarialReport', rule: 'REQUIRED', message: 'Actuarial report is required for life insurance' },
        ],
        penaltyAmount: 50000,
        penaltyCurrency: 'TTD',
      },
      {
        id: 'TT-PR-001',
        type: 'QUARTERLY',
        name: 'Prudential Report',
        description: 'Prudential metrics including risk exposure and asset quality',
        dueDay: 30,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['riskWeightedAssets', 'tier1Capital', 'tier2Capital', 'largeExposures'],
        validationRules: [
          { id: 'TT-PR-V01', field: 'tier1Capital', rule: 'MIN_VALUE', value: 0, message: 'Tier 1 capital must be positive' },
        ],
        penaltyAmount: 15000,
        penaltyCurrency: 'TTD',
      },
      {
        id: 'TT-STAT-001',
        type: 'ANNUAL',
        name: 'Insurance Statistics Return',
        description: 'Detailed insurance statistics for market analysis',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'CSV',
        requiredFields: ['policiesInForce', 'newBusiness', 'lapsedPolicies', 'claimsByCategory'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 5000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 40,
      restrictedAssets: ['cryptocurrency', 'derivatives'],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF', 'CSV'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'JM',
    name: 'Jamaica',
    region: 'Caribbean',
    regulator: {
      name: 'Financial Services Commission of Jamaica',
      shortName: 'FSC',
      website: 'https://www.fscjamaica.org',
      email: 'info@fscjamaica.org',
      phone: '+1-876-906-8400',
      address: '39-43 Barbados Avenue, Kingston 5',
    },
    currency: 'JMD',
    timezone: 'America/Jamaica',
    filingRequirements: [
      {
        id: 'JM-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Statistical Return',
        description: 'Quarterly insurance statistics and financial data',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'JSON',
        requiredFields: ['premiums', 'claims', 'reserves', 'investments'],
        validationRules: [
          { id: 'JM-QR-V01', field: 'premiums', rule: 'REQUIRED', message: 'Premium data is required' },
        ],
        penaltyAmount: 50000,
        penaltyCurrency: 'JMD',
      },
      {
        id: 'JM-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual audited financial statements and regulatory returns',
        dueDay: 30,
        dueMonth: 6,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['financialStatements', 'actuarialOpinion', 'managementReport'],
        validationRules: [],
        penaltyAmount: 200000,
        penaltyCurrency: 'JMD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 150000000,
      solvencyMarginPercent: 120,
      capitalAdequacyRatio: 1.2,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 20,
      maxForeignInvestmentPercent: 35,
      restrictedAssets: ['cryptocurrency'],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 40,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['JSON', 'PDF', 'CSV'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'BB',
    name: 'Barbados',
    region: 'Caribbean',
    regulator: {
      name: 'Financial Services Commission Barbados',
      shortName: 'FSCBB',
      website: 'https://www.fsc.gov.bb',
      email: 'info@fsc.gov.bb',
      phone: '+1-246-227-9900',
      address: '2nd Floor, BAFB Building, Belmont Road, St. Michael',
    },
    currency: 'BBD',
    timezone: 'America/Barbados',
    filingRequirements: [
      {
        id: 'BB-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Regulatory Return',
        description: 'Quarterly financial and statistical returns',
        dueDay: 30,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
        penaltyAmount: 5000,
        penaltyCurrency: 'BBD',
      },
      {
        id: 'BB-AR-001',
        type: 'ANNUAL',
        name: 'Annual Regulatory Filing',
        description: 'Annual returns with audited financials',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['auditedFinancials', 'actuarialReport'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 2500000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 40,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'GD',
    name: 'Grenada',
    region: 'Caribbean',
    regulator: {
      name: 'Grenada Authority for the Regulation of Financial Institutions',
      shortName: 'GARFIN',
      website: 'https://www.garfin.gd',
      email: 'info@garfin.gd',
      phone: '+1-473-435-2800',
      address: 'Financial Complex, The Carenage, St. George\'s',
    },
    currency: 'XCD',
    timezone: 'America/Grenada',
    filingRequirements: [
      {
        id: 'GD-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance returns',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
      },
      {
        id: 'GD-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual financial statements',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['financialStatements'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 2000000,
      solvencyMarginPercent: 120,
      capitalAdequacyRatio: 1.2,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 20,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'LC',
    name: 'Saint Lucia',
    region: 'Caribbean',
    regulator: {
      name: 'Financial Services Authority Saint Lucia',
      shortName: 'FSA',
      website: 'https://www.fsa.gov.lc',
      email: 'info@fsa.gov.lc',
      phone: '+1-758-453-3100',
      address: 'The Waterfront, Castries',
    },
    currency: 'XCD',
    timezone: 'America/St_Lucia',
    filingRequirements: [
      {
        id: 'LC-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Insurance Return',
        description: 'Quarterly insurance data submission',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
      },
      {
        id: 'LC-AR-001',
        type: 'ANNUAL',
        name: 'Annual Filing',
        description: 'Annual financial statements and returns',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['auditedFinancials'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 2000000,
      solvencyMarginPercent: 120,
      capitalAdequacyRatio: 1.2,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 20,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'VC',
    name: 'Saint Vincent & the Grenadines',
    region: 'Caribbean',
    regulator: {
      name: 'Financial Services Authority St. Vincent',
      shortName: 'FSA',
      website: 'https://www.fsa.gov.vc',
      email: 'info@fsa.gov.vc',
      phone: '+1-784-456-2400',
      address: '1st Floor, NIS Building, Upper Bay Street, Kingstown',
    },
    currency: 'XCD',
    timezone: 'America/St_Vincent',
    filingRequirements: [
      {
        id: 'VC-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Report',
        description: 'Quarterly insurance statistics',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims'],
        validationRules: [],
      },
      {
        id: 'VC-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual financial filing',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['financialStatements'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 1500000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 35,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 3,
      independentDirectorsPercent: 25,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: false,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'AG',
    name: 'Antigua & Barbuda',
    region: 'Caribbean',
    regulator: {
      name: 'Financial Services Regulatory Commission',
      shortName: 'FSRC',
      website: 'https://www.fsrc.gov.ag',
      email: 'info@fsrc.gov.ag',
      phone: '+1-268-462-2722',
      address: 'Queen Elizabeth Highway, St. John\'s',
    },
    currency: 'XCD',
    timezone: 'America/Antigua',
    filingRequirements: [
      {
        id: 'AG-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance returns',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
      },
      {
        id: 'AG-AR-001',
        type: 'ANNUAL',
        name: 'Annual Financial Return',
        description: 'Annual financial statements',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['auditedFinancials'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 2000000,
      solvencyMarginPercent: 120,
      capitalAdequacyRatio: 1.2,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 20,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'DM',
    name: 'Dominica',
    region: 'Caribbean',
    regulator: {
      name: 'Financial Services Unit',
      shortName: 'FSU',
      website: 'https://www.fsu.gov.dm',
      email: 'info@fsu.gov.dm',
      phone: '+1-767-448-3140',
      address: 'Government Headquarters, Kennedy Avenue, Roseau',
    },
    currency: 'XCD',
    timezone: 'America/Dominica',
    filingRequirements: [
      {
        id: 'DM-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Filing',
        description: 'Quarterly insurance data',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims'],
        validationRules: [],
      },
      {
        id: 'DM-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual financial statements',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['financialStatements'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 1500000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 20,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 3,
      independentDirectorsPercent: 25,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: false,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'KN',
    name: 'Saint Kitts & Nevis',
    region: 'Caribbean',
    regulator: {
      name: 'Financial Services Regulatory Commission',
      shortName: 'FSRC',
      website: 'https://www.fsrc.kn',
      email: 'info@fsrc.kn',
      phone: '+1-869-467-1019',
      address: 'The Cable Building, Cayon Street, Basseterre',
    },
    currency: 'XCD',
    timezone: 'America/St_Kitts',
    filingRequirements: [
      {
        id: 'KN-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Report',
        description: 'Quarterly insurance returns',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims'],
        validationRules: [],
      },
      {
        id: 'KN-AR-001',
        type: 'ANNUAL',
        name: 'Annual Filing',
        description: 'Annual financial statements',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['auditedFinancials'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 1500000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 35,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 3,
      independentDirectorsPercent: 25,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: false,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'BS',
    name: 'The Bahamas',
    region: 'Caribbean',
    regulator: {
      name: 'Insurance Commission of The Bahamas',
      shortName: 'ICB',
      website: 'https://www.icb.gov.bs',
      email: 'info@icb.gov.bs',
      phone: '+1-242-326-4991',
      address: 'Charlotte House, Charlotte & Shirley Streets, Nassau',
    },
    currency: 'BSD',
    timezone: 'America/Nassau',
    filingRequirements: [
      {
        id: 'BS-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance statistics',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves', 'investments'],
        validationRules: [],
        penaltyAmount: 5000,
        penaltyCurrency: 'BSD',
      },
      {
        id: 'BS-AR-001',
        type: 'ANNUAL',
        name: 'Annual Financial Statements',
        description: 'Annual audited financial statements',
        dueDay: 30,
        dueMonth: 6,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['auditedFinancials', 'actuarialReport', 'managementReport'],
        validationRules: [],
        penaltyAmount: 25000,
        penaltyCurrency: 'BSD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 5000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: ['cryptocurrency'],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 40,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'BZ',
    name: 'Belize',
    region: 'Caribbean',
    regulator: {
      name: 'Office of the Supervisor of Insurance',
      shortName: 'OSI',
      website: 'https://www.osi.gov.bz',
      email: 'info@osi.gov.bz',
      phone: '+501-223-3189',
      address: 'Mahogany Street Extension, Belmopan',
    },
    currency: 'BZD',
    timezone: 'America/Belize',
    filingRequirements: [
      {
        id: 'BZ-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance data',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims'],
        validationRules: [],
      },
      {
        id: 'BZ-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual financial statements',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['auditedFinancials'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 1000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 20,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 3,
      independentDirectorsPercent: 25,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: false,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'GY',
    name: 'Guyana',
    region: 'Caribbean',
    regulator: {
      name: 'Insurance Supervisory Authority',
      shortName: 'ISA',
      website: 'https://www.isa.gov.gy',
      email: 'info@isa.gov.gy',
      phone: '+592-226-5708',
      address: '61 High Street, Kingston, Georgetown',
    },
    currency: 'GYD',
    timezone: 'America/Guyana',
    filingRequirements: [
      {
        id: 'GY-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Insurance Return',
        description: 'Quarterly insurance data submission',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
      },
      {
        id: 'GY-AR-001',
        type: 'ANNUAL',
        name: 'Annual Financial Filing',
        description: 'Annual financial statements',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['auditedFinancials'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 200000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'SR',
    name: 'Suriname',
    region: 'Caribbean',
    regulator: {
      name: 'Centrale Bank van Suriname',
      shortName: 'CBvS',
      website: 'https://www.cbvs.sr',
      email: 'info@cbvs.sr',
      phone: '+597-472-700',
      address: 'Waterkant 20, Paramaribo',
    },
    currency: 'SRD',
    timezone: 'America/Paramaribo',
    filingRequirements: [
      {
        id: 'SR-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance returns',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims'],
        validationRules: [],
      },
      {
        id: 'SR-AR-001',
        type: 'ANNUAL',
        name: 'Annual Filing',
        description: 'Annual financial statements',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['financialStatements'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 50000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 35,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
];

// ============================================================================
// LATIN AMERICA JURISDICTIONS
// ============================================================================

export const LATIN_AMERICA_JURISDICTIONS: JurisdictionConfig[] = [
  {
    code: 'PA',
    name: 'Panama',
    region: 'Latin America',
    regulator: {
      name: 'Superintendencia de Seguros y Reaseguros de Panamá',
      shortName: 'SSRP',
      website: 'https://www.ssrp.gob.pa',
      email: 'info@ssrp.gob.pa',
      phone: '+507-369-2500',
      address: 'Via España, Edificio Omega, Panamá',
    },
    currency: 'PAB',
    timezone: 'America/Panama',
    filingRequirements: [
      {
        id: 'PA-QR-001',
        type: 'QUARTERLY',
        name: 'Informe Trimestral',
        description: 'Informe estadístico y financiero trimestral',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'XML',
        requiredFields: ['primas', 'siniestros', 'reservas'],
        validationRules: [],
        penaltyAmount: 5000,
        penaltyCurrency: 'PAB',
      },
      {
        id: 'PA-AR-001',
        type: 'ANNUAL',
        name: 'Estados Financieros Anuales',
        description: 'Estados financieros auditados anuales',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['estadosFinancieros', 'dictamenActuarial'],
        validationRules: [],
        penaltyAmount: 25000,
        penaltyCurrency: 'PAB',
      },
    ],
    capitalRequirements: {
      minimumCapital: 2500000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 30,
      maxForeignInvestmentPercent: 45,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 40,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    region: 'Latin America',
    regulator: {
      name: 'Superintendencia General de Seguros',
      shortName: 'SUGESE',
      website: 'https://www.sugese.fi.cr',
      email: 'consultas@sugese.fi.cr',
      phone: '+506-2547-3200',
      address: 'La Uruca, San José',
    },
    currency: 'CRC',
    timezone: 'America/Costa_Rica',
    filingRequirements: [
      {
        id: 'CR-QR-001',
        type: 'QUARTERLY',
        name: 'Informe Trimestral',
        description: 'Reporte trimestral de seguros',
        dueDay: 15,
        graceDays: 10,
        dataFormat: 'XBRL',
        requiredFields: ['primas', 'siniestros', 'reservas'],
        validationRules: [],
      },
      {
        id: 'CR-AR-001',
        type: 'ANNUAL',
        name: 'Estados Financieros',
        description: 'Estados financieros anuales auditados',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['estadosFinancieros'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 500000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 40,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 40,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'GT',
    name: 'Guatemala',
    region: 'Latin America',
    regulator: {
      name: 'Superintendencia de Bancos de Guatemala',
      shortName: 'SIB',
      website: 'https://www.sib.gob.gt',
      email: 'info@sib.gob.gt',
      phone: '+502-2421-0000',
      address: '7a. Avenida 22-72, Zona 1, Ciudad de Guatemala',
    },
    currency: 'GTQ',
    timezone: 'America/Guatemala',
    filingRequirements: [
      {
        id: 'GT-QR-001',
        type: 'QUARTERLY',
        name: 'Informe Trimestral',
        description: 'Reporte trimestral de seguros',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'XML',
        requiredFields: ['primas', 'siniestros'],
        validationRules: [],
      },
      {
        id: 'GT-AR-001',
        type: 'ANNUAL',
        name: 'Estados Financieros Anuales',
        description: 'Estados financieros anuales',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['estadosFinancieros'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 50000000,
      solvencyMarginPercent: 120,
      capitalAdequacyRatio: 1.2,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 35,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'HN',
    name: 'Honduras',
    region: 'Latin America',
    regulator: {
      name: 'Comisión Nacional de Bancos y Seguros',
      shortName: 'CNBS',
      website: 'https://www.cnbs.gob.hn',
      email: 'info@cnbs.gob.hn',
      phone: '+504-2232-5200',
      address: 'Col. Los Castaños, Tegucigalpa',
    },
    currency: 'HNL',
    timezone: 'America/Tegucigalpa',
    filingRequirements: [
      {
        id: 'HN-QR-001',
        type: 'QUARTERLY',
        name: 'Informe Trimestral',
        description: 'Reporte trimestral de seguros',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['primas', 'siniestros'],
        validationRules: [],
      },
      {
        id: 'HN-AR-001',
        type: 'ANNUAL',
        name: 'Estados Financieros',
        description: 'Estados financieros anuales',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['estadosFinancieros'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 50000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'SV',
    name: 'El Salvador',
    region: 'Latin America',
    regulator: {
      name: 'Superintendencia del Sistema Financiero',
      shortName: 'SSF',
      website: 'https://www.ssf.gob.sv',
      email: 'info@ssf.gob.sv',
      phone: '+503-2281-5000',
      address: 'Centro de Gobierno, San Salvador',
    },
    currency: 'USD',
    timezone: 'America/El_Salvador',
    filingRequirements: [
      {
        id: 'SV-QR-001',
        type: 'QUARTERLY',
        name: 'Informe Trimestral',
        description: 'Reporte trimestral de seguros',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'XML',
        requiredFields: ['primas', 'siniestros', 'reservas'],
        validationRules: [],
      },
      {
        id: 'SV-AR-001',
        type: 'ANNUAL',
        name: 'Estados Financieros Anuales',
        description: 'Estados financieros anuales auditados',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['estadosFinancieros'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 3000000,
      solvencyMarginPercent: 120,
      capitalAdequacyRatio: 1.2,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 40,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'NI',
    name: 'Nicaragua',
    region: 'Latin America',
    regulator: {
      name: 'Superintendencia de Bancos y de Otras Instituciones Financieras',
      shortName: 'SIBOIF',
      website: 'https://www.siboif.gob.ni',
      email: 'info@siboif.gob.ni',
      phone: '+505-2255-4000',
      address: 'Frente a la Nueva Catedral, Managua',
    },
    currency: 'NIO',
    timezone: 'America/Managua',
    filingRequirements: [
      {
        id: 'NI-QR-001',
        type: 'QUARTERLY',
        name: 'Informe Trimestral',
        description: 'Reporte trimestral de seguros',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['primas', 'siniestros'],
        validationRules: [],
      },
      {
        id: 'NI-AR-001',
        type: 'ANNUAL',
        name: 'Estados Financieros',
        description: 'Estados financieros anuales',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['estadosFinancieros'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 100000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 15,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: false,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    region: 'Latin America',
    regulator: {
      name: 'Superintendencia de Seguros',
      shortName: 'SIS',
      website: 'https://www.sis.gob.do',
      email: 'info@sis.gob.do',
      phone: '+1-809-567-5500',
      address: 'Av. Winston Churchill, Santo Domingo',
    },
    currency: 'DOP',
    timezone: 'America/Santo_Domingo',
    filingRequirements: [
      {
        id: 'DO-QR-001',
        type: 'QUARTERLY',
        name: 'Informe Trimestral',
        description: 'Reporte trimestral de seguros',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'XML',
        requiredFields: ['primas', 'siniestros', 'reservas'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'DOP',
      },
      {
        id: 'DO-AR-001',
        type: 'ANNUAL',
        name: 'Estados Financieros Anuales',
        description: 'Estados financieros anuales auditados',
        dueDay: 31,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['estadosFinancieros', 'dictamenActuarial'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'DOP',
      },
    ],
    capitalRequirements: {
      minimumCapital: 100000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 40,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 40,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
    region: 'Latin America',
    regulator: {
      name: 'Office of the Commissioner of Insurance of Puerto Rico',
      shortName: 'OCI',
      website: 'https://www.ocif.pr.gov',
      email: 'info@ocif.pr.gov',
      phone: '+1-787-722-8686',
      address: '1400 Eduardo Dato, San Juan',
    },
    currency: 'USD',
    timezone: 'America/Puerto_Rico',
    filingRequirements: [
      {
        id: 'PR-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Statement',
        description: 'Quarterly financial statement',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['premiums', 'losses', 'reserves', 'surplus'],
        validationRules: [],
        penaltyAmount: 5000,
        penaltyCurrency: 'USD',
      },
      {
        id: 'PR-AR-001',
        type: 'ANNUAL',
        name: 'Annual Statement',
        description: 'Annual financial statement with actuarial opinion',
        dueDay: 60,
        dueMonth: 3,
        graceDays: 15,
        dataFormat: 'XBRL',
        requiredFields: ['annualStatement', 'actuarialOpinion', 'auditedFinancials'],
        validationRules: [],
        penaltyAmount: 25000,
        penaltyCurrency: 'USD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 5000000,
      solvencyMarginPercent: 200,
      capitalAdequacyRatio: 2.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 20,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 7,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'STATUTORY',
  },
];

// ============================================================================
// EUROPE JURISDICTIONS
// ============================================================================

export const EUROPE_JURISDICTIONS: JurisdictionConfig[] = [
  {
    code: 'GB',
    name: 'United Kingdom',
    region: 'Europe',
    regulator: {
      name: 'Prudential Regulation Authority',
      shortName: 'PRA',
      website: 'https://www.bankofengland.co.uk/pra',
      email: 'pra@bankofengland.co.uk',
      phone: '+44-20-3461-7000',
      address: '20 Moorgate, London EC2R 6DA',
    },
    currency: 'GBP',
    timezone: 'Europe/London',
    filingRequirements: [
      {
        id: 'GB-QR-001',
        type: 'QUARTERLY',
        name: 'Quantitative Reporting Templates',
        description: 'Solvency II QRT submission',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['balanceSheet', 'riskMargin', 'technicalProvisions', 'SCR', 'MCR'],
        validationRules: [
          { id: 'GB-QR-V01', field: 'SCR', rule: 'MIN_VALUE', value: 0, message: 'SCR must be positive' },
          { id: 'GB-QR-V02', field: 'MCR', rule: 'MIN_VALUE', value: 0, message: 'MCR must be positive' },
        ],
        penaltyAmount: 50000,
        penaltyCurrency: 'GBP',
      },
      {
        id: 'GB-AR-001',
        type: 'ANNUAL',
        name: 'Solvency and Financial Condition Report',
        description: 'Annual SFCR under Solvency II',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['businessOverview', 'governance', 'riskProfile', 'valuation', 'capitalManagement'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'GBP',
      },
      {
        id: 'GB-NQ-001',
        type: 'QUARTERLY',
        name: 'Narrative Report',
        description: 'Quarterly narrative report on significant events',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['significantEvents', 'riskExposure', 'outlook'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 1250000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 40,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: ['cryptocurrency'],
    },
    governanceRequirements: {
      minBoardMembers: 7,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'DE',
    name: 'Germany',
    region: 'Europe',
    regulator: {
      name: 'Bundesanstalt für Finanzdienstleistungsaufsicht',
      shortName: 'BaFin',
      website: 'https://www.bafin.de',
      email: 'poststelle@bafin.de',
      phone: '+49-228-4140-0',
      address: 'Graurheindorfer Straße 108, 53117 Bonn',
    },
    currency: 'EUR',
    timezone: 'Europe/Berlin',
    filingRequirements: [
      {
        id: 'DE-QR-001',
        type: 'QUARTERLY',
        name: 'Quartalsbericht',
        description: 'Solvency II quarterly reporting',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['bilanz', 'risikomarge', 'technischeRueckstellungen'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'EUR',
      },
      {
        id: 'DE-AR-001',
        type: 'ANNUAL',
        name: 'Solvency and Financial Condition Report',
        description: 'Annual SFCR',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['solvabilitaetsbericht'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'EUR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 1250000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'FR',
    name: 'France',
    region: 'Europe',
    regulator: {
      name: 'Autorité de Contrôle Prudentiel et de Résolution',
      shortName: 'ACPR',
      website: 'https://acpr.banque-france.fr',
      email: 'acpr@acpr.banque-france.fr',
      phone: '+33-1-49-95-40-00',
      address: '4 Place de Budapest, 75009 Paris',
    },
    currency: 'EUR',
    timezone: 'Europe/Paris',
    filingRequirements: [
      {
        id: 'FR-QR-001',
        type: 'QUARTERLY',
        name: 'Rapport Trimestriel',
        description: 'Rapport trimestriel Solvabilité II',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['bilan', 'margeRisque', 'provisionsTechniques'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'EUR',
      },
      {
        id: 'FR-AR-001',
        type: 'ANNUAL',
        name: 'Rapport sur la Solvabilité et la Situation Financière',
        description: 'Rapport annuel SFCR',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['rSF'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'EUR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 1250000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'IE',
    name: 'Ireland',
    region: 'Europe',
    regulator: {
      name: 'Central Bank of Ireland',
      shortName: 'CBI',
      website: 'https://www.centralbank.ie',
      email: 'info@centralbank.ie',
      phone: '+353-1-224-6000',
      address: 'Bishop Street, Dublin 4',
    },
    currency: 'EUR',
    timezone: 'Europe/Dublin',
    filingRequirements: [
      {
        id: 'IE-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Reporting Templates',
        description: 'Solvency II QRTs',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['balanceSheet', 'technicalProvisions', 'SCR', 'MCR'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'EUR',
      },
      {
        id: 'IE-AR-001',
        type: 'ANNUAL',
        name: 'Solvency and Financial Condition Report',
        description: 'Annual SFCR',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['SFCR'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'EUR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 1250000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 40,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 55,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    region: 'Europe',
    regulator: {
      name: 'De Nederlandsche Bank',
      shortName: 'DNB',
      website: 'https://www.dnb.nl',
      email: 'info@dnb.nl',
      phone: '+31-20-524-9111',
      address: 'PO Box 98, 1000 AB Amsterdam',
    },
    currency: 'EUR',
    timezone: 'Europe/Amsterdam',
    filingRequirements: [
      {
        id: 'NL-QR-001',
        type: 'QUARTERLY',
        name: 'Kwartaalrapportage',
        description: 'Solvency II kwartaalrapportage',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['balans', 'technischeVoorzieningen', 'SCR', 'MCR'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'EUR',
      },
      {
        id: 'NL-AR-001',
        type: 'ANNUAL',
        name: 'Solvency and Financial Condition Report',
        description: 'Jaarlijkse SFCR',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['SFCR'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'EUR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 1250000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    region: 'Europe',
    regulator: {
      name: 'Swiss Financial Market Supervisory Authority',
      shortName: 'FINMA',
      website: 'https://www.finma.ch',
      email: 'info@finma.ch',
      phone: '+41-31-327-91-00',
      address: 'Laupenstrasse 27, 3003 Bern',
    },
    currency: 'CHF',
    timezone: 'Europe/Zurich',
    filingRequirements: [
      {
        id: 'CH-QR-001',
        type: 'QUARTERLY',
        name: 'Quartalsbericht',
        description: 'Swiss Solvency Test quarterly report',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['sstCapital', 'riskExposure', 'investments'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'CHF',
      },
      {
        id: 'CH-AR-001',
        type: 'ANNUAL',
        name: 'Annual Report',
        description: 'Annual report including SST results',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['annualReport', 'sstReport'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'CHF',
      },
    ],
    capitalRequirements: {
      minimumCapital: 2000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    region: 'Europe',
    regulator: {
      name: 'Commissariat aux Assurances',
      shortName: 'CAA',
      website: 'https://www.caa.lu',
      email: 'info@caa.lu',
      phone: '+352-22-69-11-1',
      address: '7 boulevard Royal, 2449 Luxembourg',
    },
    currency: 'EUR',
    timezone: 'Europe/Luxembourg',
    filingRequirements: [
      {
        id: 'LU-QR-001',
        type: 'QUARTERLY',
        name: 'Rapport Trimestriel',
        description: 'Solvency II QRTs',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['balanceSheet', 'technicalProvisions', 'SCR', 'MCR'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'EUR',
      },
      {
        id: 'LU-AR-001',
        type: 'ANNUAL',
        name: 'Rapport SFCR',
        description: 'Annual SFCR',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['SFCR'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'EUR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 1250000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 40,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 60,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'MT',
    name: 'Malta',
    region: 'Europe',
    regulator: {
      name: 'Malta Financial Services Authority',
      shortName: 'MFSA',
      website: 'https://www.mfsa.mt',
      email: 'info@mfsa.mt',
      phone: '+356-2144-1155',
      address: 'Notabile Road, Attard BKR 3000',
    },
    currency: 'EUR',
    timezone: 'Europe/Malta',
    filingRequirements: [
      {
        id: 'MT-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Reporting',
        description: 'Solvency II QRTs',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['balanceSheet', 'technicalProvisions', 'SCR', 'MCR'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'EUR',
      },
      {
        id: 'MT-AR-001',
        type: 'ANNUAL',
        name: 'SFCR',
        description: 'Annual SFCR',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['SFCR'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'EUR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 1250000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 40,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 55,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'CY',
    name: 'Cyprus',
    region: 'Europe',
    regulator: {
      name: 'Insurance Companies Control Service',
      shortName: 'ICCS',
      website: 'https://www.mof.gov.cy/iccs',
      email: 'iccs@mof.gov.cy',
      phone: '+357-22-602-800',
      address: 'Corner of Esperidon & Aischinou Streets, Nicosia',
    },
    currency: 'EUR',
    timezone: 'Asia/Nicosia',
    filingRequirements: [
      {
        id: 'CY-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Reporting',
        description: 'Solvency II QRTs',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['balanceSheet', 'technicalProvisions', 'SCR', 'MCR'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'EUR',
      },
      {
        id: 'CY-AR-001',
        type: 'ANNUAL',
        name: 'SFCR',
        description: 'Annual SFCR',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['SFCR'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'EUR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 1250000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
];

// ============================================================================
// NORTH AMERICA JURISDICTIONS
// ============================================================================

export const NORTH_AMERICA_JURISDICTIONS: JurisdictionConfig[] = [
  {
    code: 'US-NY',
    name: 'New York, USA',
    region: 'North America',
    regulator: {
      name: 'New York State Department of Financial Services',
      shortName: 'NY DFS',
      website: 'https://www.dfs.ny.gov',
      email: 'licensing@dfs.ny.gov',
      phone: '+1-212-709-5500',
      address: 'One State Street, New York, NY 10004',
    },
    currency: 'USD',
    timezone: 'America/New_York',
    filingRequirements: [
      {
        id: 'US-NY-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Statement',
        description: 'NAIC quarterly statement',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['premiums', 'losses', 'reserves', 'surplus', 'assets'],
        validationRules: [
          { id: 'US-NY-QR-V01', field: 'surplus', rule: 'MIN_VALUE', value: 0, message: 'Policyholder surplus must be positive' },
        ],
        penaltyAmount: 10000,
        penaltyCurrency: 'USD',
      },
      {
        id: 'US-NY-AR-001',
        type: 'ANNUAL',
        name: 'Annual Statement',
        description: 'NAIC annual statement with actuarial opinion',
        dueDay: 60,
        dueMonth: 3,
        graceDays: 15,
        dataFormat: 'XBRL',
        requiredFields: ['annualStatement', 'actuarialOpinion', 'managementDiscussion'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'USD',
      },
      {
        id: 'US-NY-RBC-001',
        type: 'ANNUAL',
        name: 'Risk-Based Capital Report',
        description: 'Annual RBC calculation and report',
        dueDay: 60,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['rbcCalculation', 'companyActionLevel', 'regulatoryActionLevel'],
        validationRules: [],
      },
    ],
    capitalRequirements: {
      minimumCapital: 2000000,
      solvencyMarginPercent: 200,
      capitalAdequacyRatio: 2.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 3,
      maxPropertyPercent: 10,
      maxForeignInvestmentPercent: 20,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 7,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'STATUTORY',
  },
  {
    code: 'US-FL',
    name: 'Florida, USA',
    region: 'North America',
    regulator: {
      name: 'Florida Office of Insurance Regulation',
      shortName: 'FLOIR',
      website: 'https://www.floir.com',
      email: 'consumer.assistance@floir.com',
      phone: '+1-850-413-3100',
      address: '200 East Gaines Street, Tallahassee, FL 32301',
    },
    currency: 'USD',
    timezone: 'America/New_York',
    filingRequirements: [
      {
        id: 'US-FL-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Statement',
        description: 'NAIC quarterly statement',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['premiums', 'losses', 'reserves'],
        validationRules: [],
        penaltyAmount: 10000,
        penaltyCurrency: 'USD',
      },
      {
        id: 'US-FL-AR-001',
        type: 'ANNUAL',
        name: 'Annual Statement',
        description: 'NAIC annual statement',
        dueDay: 60,
        dueMonth: 3,
        graceDays: 15,
        dataFormat: 'XBRL',
        requiredFields: ['annualStatement', 'actuarialOpinion'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'USD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 2000000,
      solvencyMarginPercent: 200,
      capitalAdequacyRatio: 2.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 3,
      maxPropertyPercent: 10,
      maxForeignInvestmentPercent: 20,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 7,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'STATUTORY',
  },
  {
    code: 'US-TX',
    name: 'Texas, USA',
    region: 'North America',
    regulator: {
      name: 'Texas Department of Insurance',
      shortName: 'TDI',
      website: 'https://www.tdi.texas.gov',
      email: 'consumer@tdi.texas.gov',
      phone: '+1-512-463-6169',
      address: '333 Guadalupe Street, Austin, TX 78701',
    },
    currency: 'USD',
    timezone: 'America/Chicago',
    filingRequirements: [
      {
        id: 'US-TX-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Statement',
        description: 'NAIC quarterly statement',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['premiums', 'losses', 'reserves'],
        validationRules: [],
        penaltyAmount: 10000,
        penaltyCurrency: 'USD',
      },
      {
        id: 'US-TX-AR-001',
        type: 'ANNUAL',
        name: 'Annual Statement',
        description: 'NAIC annual statement',
        dueDay: 60,
        dueMonth: 3,
        graceDays: 15,
        dataFormat: 'XBRL',
        requiredFields: ['annualStatement', 'actuarialOpinion'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'USD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 2000000,
      solvencyMarginPercent: 200,
      capitalAdequacyRatio: 2.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 3,
      maxPropertyPercent: 10,
      maxForeignInvestmentPercent: 20,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 7,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'STATUTORY',
  },
  {
    code: 'US-CA',
    name: 'California, USA',
    region: 'North America',
    regulator: {
      name: 'California Department of Insurance',
      shortName: 'CDI',
      website: 'https://www.insurance.ca.gov',
      email: 'consumer.services@insurance.ca.gov',
      phone: '+1-800-927-4357',
      address: '300 South Spring Street, Los Angeles, CA 90013',
    },
    currency: 'USD',
    timezone: 'America/Los_Angeles',
    filingRequirements: [
      {
        id: 'US-CA-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Statement',
        description: 'NAIC quarterly statement',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XBRL',
        requiredFields: ['premiums', 'losses', 'reserves'],
        validationRules: [],
        penaltyAmount: 10000,
        penaltyCurrency: 'USD',
      },
      {
        id: 'US-CA-AR-001',
        type: 'ANNUAL',
        name: 'Annual Statement',
        description: 'NAIC annual statement',
        dueDay: 60,
        dueMonth: 3,
        graceDays: 15,
        dataFormat: 'XBRL',
        requiredFields: ['annualStatement', 'actuarialOpinion'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'USD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 2000000,
      solvencyMarginPercent: 200,
      capitalAdequacyRatio: 2.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 3,
      maxPropertyPercent: 10,
      maxForeignInvestmentPercent: 20,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 7,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XBRL', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'STATUTORY',
  },
  {
    code: 'CA-ON',
    name: 'Ontario, Canada',
    region: 'North America',
    regulator: {
      name: 'Financial Services Regulatory Authority of Ontario',
      shortName: 'FSRA',
      website: 'https://www.fsrao.ca',
      email: 'contactcentre@fsrao.ca',
      phone: '+1-800-668-0128',
      address: '25 Sheppard Avenue West, Suite 100, Toronto, ON M2N 6S6',
    },
    currency: 'CAD',
    timezone: 'America/Toronto',
    filingRequirements: [
      {
        id: 'CA-ON-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly financial return',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves', 'capital'],
        validationRules: [],
        penaltyAmount: 15000,
        penaltyCurrency: 'CAD',
      },
      {
        id: 'CA-ON-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual audited financial statements',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialOpinion', 'auditedFinancials'],
        validationRules: [],
        penaltyAmount: 75000,
        penaltyCurrency: 'CAD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 5000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'CA-QC',
    name: 'Quebec, Canada',
    region: 'North America',
    regulator: {
      name: 'Autorité des marchés financiers',
      shortName: 'AMF',
      website: 'https://lautorite.qc.ca',
      email: 'info@lautorite.qc.ca',
      phone: '+1-514-395-0337',
      address: '800 René-Lévesque Blvd West, Suite 700, Montreal, QC H3B 4N1',
    },
    currency: 'CAD',
    timezone: 'America/Montreal',
    filingRequirements: [
      {
        id: 'CA-QC-QR-001',
        type: 'QUARTERLY',
        name: 'Rapport Trimestriel',
        description: 'Rapport financier trimestriel',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['primes', 'sinistres', 'reserves', 'capitaux'],
        validationRules: [],
        penaltyAmount: 15000,
        penaltyCurrency: 'CAD',
      },
      {
        id: 'CA-QC-AR-001',
        type: 'ANNUAL',
        name: 'Rapport Annuel',
        description: 'États financiers annuels audités',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['rapportAnnuel', 'opinionActuarielle', 'etatsFinanciers'],
        validationRules: [],
        penaltyAmount: 75000,
        penaltyCurrency: 'CAD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 5000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
];

// ============================================================================
// ASIA-PACIFIC JURISDICTIONS
// ============================================================================

export const ASIA_PACIFIC_JURISDICTIONS: JurisdictionConfig[] = [
  {
    code: 'SG',
    name: 'Singapore',
    region: 'Asia-Pacific',
    regulator: {
      name: 'Monetary Authority of Singapore',
      shortName: 'MAS',
      website: 'https://www.mas.gov.sg',
      email: 'webmaster@mas.gov.sg',
      phone: '+65-6225-5577',
      address: '10 Shenton Way, MAS Building, Singapore 079117',
    },
    currency: 'SGD',
    timezone: 'Asia/Singapore',
    filingRequirements: [
      {
        id: 'SG-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Statistics Return',
        description: 'RBC framework quarterly statistics',
        dueDay: 30,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves', 'capital', 'investments'],
        validationRules: [],
        penaltyAmount: 20000,
        penaltyCurrency: 'SGD',
      },
      {
        id: 'SG-AR-001',
        type: 'ANNUAL',
        name: 'Annual Returns',
        description: 'Annual audited financial statements',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport', 'auditedFinancials'],
        validationRules: [],
        penaltyAmount: 100000,
        penaltyCurrency: 'SGD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 5000000,
      solvencyMarginPercent: 120,
      capitalAdequacyRatio: 1.2,
    },
    investmentLimits: {
      maxEquityPercent: 40,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 30,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    region: 'Asia-Pacific',
    regulator: {
      name: 'Insurance Authority of Hong Kong',
      shortName: 'IA',
      website: 'https://www.ia.org.hk',
      email: 'enquiry@ia.org.hk',
      phone: '+852-2867-2567',
      address: '19/F, Queensway Government Offices, 66 Queensway, Hong Kong',
    },
    currency: 'HKD',
    timezone: 'Asia/Hong_Kong',
    filingRequirements: [
      {
        id: 'HK-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance statistics',
        dueDay: 30,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'HKD',
      },
      {
        id: 'HK-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual financial statements',
        dueDay: 60,
        dueMonth: 6,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport'],
        validationRules: [],
        penaltyAmount: 200000,
        penaltyCurrency: 'HKD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 10000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'JP',
    name: 'Japan',
    region: 'Asia-Pacific',
    regulator: {
      name: 'Financial Services Agency of Japan',
      shortName: 'FSA',
      website: 'https://www.fsa.go.jp',
      email: 'webmaster@fsa.go.jp',
      phone: '+81-3-3506-6000',
      address: '3-2-1 Kasumigaseki, Chiyoda-ku, Tokyo 100-8967',
    },
    currency: 'JPY',
    timezone: 'Asia/Tokyo',
    filingRequirements: [
      {
        id: 'JP-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Report',
        description: 'Quarterly insurance business report',
        dueDay: 45,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
        penaltyAmount: 1000000,
        penaltyCurrency: 'JPY',
      },
      {
        id: 'JP-AR-001',
        type: 'ANNUAL',
        name: 'Annual Report',
        description: 'Annual business and financial report',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['annualReport', 'actuarialOpinion'],
        validationRules: [],
        penaltyAmount: 5000000,
        penaltyCurrency: 'JPY',
      },
    ],
    capitalRequirements: {
      minimumCapital: 1000000000,
      solvencyMarginPercent: 200,
      capitalAdequacyRatio: 2.0,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 30,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'AU',
    name: 'Australia',
    region: 'Asia-Pacific',
    regulator: {
      name: 'Australian Prudential Regulation Authority',
      shortName: 'APRA',
      website: 'https://www.apra.gov.au',
      email: 'info@apra.gov.au',
      phone: '+61-2-9210-3000',
      address: 'Level 18, 400 George Street, Sydney NSW 2000',
    },
    currency: 'AUD',
    timezone: 'Australia/Sydney',
    filingRequirements: [
      {
        id: 'AU-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Statistics',
        description: 'APRA quarterly insurance statistics',
        dueDay: 20,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves', 'capital'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'AUD',
      },
      {
        id: 'AU-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual audited financial statements',
        dueDay: 60,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport', 'auditedFinancials'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'AUD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 10000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    region: 'Asia-Pacific',
    regulator: {
      name: 'Reserve Bank of New Zealand',
      shortName: 'RBNZ',
      website: 'https://www.rbnz.govt.nz',
      email: 'webteam@rbnz.govt.nz',
      phone: '+64-4-471-3760',
      address: '2 The Terrace, Wellington 6011',
    },
    currency: 'NZD',
    timezone: 'Pacific/Auckland',
    filingRequirements: [
      {
        id: 'NZ-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance statistics',
        dueDay: 30,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
        penaltyAmount: 25000,
        penaltyCurrency: 'NZD',
      },
      {
        id: 'NZ-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual financial statements',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport'],
        validationRules: [],
        penaltyAmount: 100000,
        penaltyCurrency: 'NZD',
      },
    ],
    capitalRequirements: {
      minimumCapital: 5000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
];

// ============================================================================
// AFRICA JURISDICTIONS
// ============================================================================

export const AFRICA_JURISDICTIONS: JurisdictionConfig[] = [
  {
    code: 'ZA',
    name: 'South Africa',
    region: 'Africa',
    regulator: {
      name: 'Financial Sector Conduct Authority',
      shortName: 'FSCA',
      website: 'https://www.fsca.co.za',
      email: 'info@fsca.co.za',
      phone: '+27-12-428-8000',
      address: 'River Park, 1 Matlala Road, Sunnyside, Pretoria',
    },
    currency: 'ZAR',
    timezone: 'Africa/Johannesburg',
    filingRequirements: [
      {
        id: 'ZA-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'SAM framework quarterly return',
        dueDay: 30,
        graceDays: 0,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves', 'SCR', 'MCR'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'ZAR',
      },
      {
        id: 'ZA-AR-001',
        type: 'ANNUAL',
        name: 'Annual Financial Statements',
        description: 'Annual audited financial statements',
        dueDay: 90,
        dueMonth: 6,
        graceDays: 0,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport', 'auditedFinancials'],
        validationRules: [],
        penaltyAmount: 500000,
        penaltyCurrency: 'ZAR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 10000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 5,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 40,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 50,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: true,
    reportingBasis: 'IFRS',
  },
  {
    code: 'MU',
    name: 'Mauritius',
    region: 'Africa',
    regulator: {
      name: 'Financial Services Commission Mauritius',
      shortName: 'FSC',
      website: 'https://www.fscmauritius.org',
      email: 'info@fscmauritius.org',
      phone: '+230-403-7000',
      address: 'One Cathedral Square, 1 Jules Koenig Street, Port Louis',
    },
    currency: 'MUR',
    timezone: 'Indian/Mauritius',
    filingRequirements: [
      {
        id: 'MU-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance return',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'MUR',
      },
      {
        id: 'MU-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual audited financial statements',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'MUR',
      },
    ],
    capitalRequirements: {
      minimumCapital: 50000000,
      solvencyMarginPercent: 120,
      capitalAdequacyRatio: 1.2,
    },
    investmentLimits: {
      maxEquityPercent: 35,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 30,
      maxForeignInvestmentPercent: 50,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 40,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'KE',
    name: 'Kenya',
    region: 'Africa',
    regulator: {
      name: 'Insurance Regulatory Authority of Kenya',
      shortName: 'IRA',
      website: 'https://www.ira.go.ke',
      email: 'info@ira.go.ke',
      phone: '+254-20-271-4026',
      address: 'Zep-Re Place, Upper Hill, Nairobi',
    },
    currency: 'KES',
    timezone: 'Africa/Nairobi',
    filingRequirements: [
      {
        id: 'KE-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Returns',
        description: 'Quarterly insurance returns',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'KES',
      },
      {
        id: 'KE-AR-001',
        type: 'ANNUAL',
        name: 'Annual Return',
        description: 'Annual audited accounts',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'KES',
      },
    ],
    capitalRequirements: {
      minimumCapital: 600000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 40,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'NG',
    name: 'Nigeria',
    region: 'Africa',
    regulator: {
      name: 'National Insurance Commission',
      shortName: 'NAICOM',
      website: 'https://www.naicom.gov.ng',
      email: 'info@naicom.gov.ng',
      phone: '+234-9-291-5345',
      address: 'Plot 419, Cadastral Zone B4, Durumi District, Abuja',
    },
    currency: 'NGN',
    timezone: 'Africa/Lagos',
    filingRequirements: [
      {
        id: 'NG-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Returns',
        description: 'Quarterly statutory returns',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'XML',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
        penaltyAmount: 100000,
        penaltyCurrency: 'NGN',
      },
      {
        id: 'NG-AR-001',
        type: 'ANNUAL',
        name: 'Annual Statutory Returns',
        description: 'Annual audited financial statements',
        dueDay: 90,
        dueMonth: 6,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport'],
        validationRules: [],
        penaltyAmount: 500000,
        penaltyCurrency: 'NGN',
      },
    ],
    capitalRequirements: {
      minimumCapital: 10000000000,
      solvencyMarginPercent: 150,
      capitalAdequacyRatio: 1.5,
    },
    investmentLimits: {
      maxEquityPercent: 30,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 35,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 7,
      independentDirectorsPercent: 40,
      auditCommitteeRequired: true,
      riskCommitteeRequired: true,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['XML', 'PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
  {
    code: 'EG',
    name: 'Egypt',
    region: 'Africa',
    regulator: {
      name: 'Egyptian Financial Supervisory Authority',
      shortName: 'EFSA',
      website: 'https://www.efsa.gov.eg',
      email: 'info@efsa.gov.eg',
      phone: '+20-2-3534-7212',
      address: 'Smart Village, Building 3, Giza',
    },
    currency: 'EGP',
    timezone: 'Africa/Cairo',
    filingRequirements: [
      {
        id: 'EG-QR-001',
        type: 'QUARTERLY',
        name: 'Quarterly Return',
        description: 'Quarterly insurance statistics',
        dueDay: 30,
        graceDays: 15,
        dataFormat: 'PDF',
        requiredFields: ['premiums', 'claims', 'reserves'],
        validationRules: [],
        penaltyAmount: 50000,
        penaltyCurrency: 'EGP',
      },
      {
        id: 'EG-AR-001',
        type: 'ANNUAL',
        name: 'Annual Financial Statements',
        description: 'Annual audited accounts',
        dueDay: 90,
        dueMonth: 3,
        graceDays: 30,
        dataFormat: 'PDF',
        requiredFields: ['annualReturn', 'actuarialReport'],
        validationRules: [],
        penaltyAmount: 250000,
        penaltyCurrency: 'EGP',
      },
    ],
    capitalRequirements: {
      minimumCapital: 150000000,
      solvencyMarginPercent: 100,
      capitalAdequacyRatio: 1.0,
    },
    investmentLimits: {
      maxEquityPercent: 25,
      maxSingleIssuerPercent: 10,
      maxPropertyPercent: 25,
      maxForeignInvestmentPercent: 30,
      restrictedAssets: [],
    },
    governanceRequirements: {
      minBoardMembers: 5,
      independentDirectorsPercent: 33,
      auditCommitteeRequired: true,
      riskCommitteeRequired: false,
      actuaryRequired: true,
      complianceOfficerRequired: true,
    },
    dataFormatPreferences: ['PDF'],
    electronicSubmissionEnabled: true,
    digitalSignatureRequired: false,
    reportingBasis: 'IFRS',
  },
];

// ============================================================================
// ALL JURISDICTIONS COMBINED
// ============================================================================

export const ALL_JURISDICTIONS: JurisdictionConfig[] = [
  ...CARIBBEAN_JURISDICTIONS,
  ...LATIN_AMERICA_JURISDICTIONS,
  ...EUROPE_JURISDICTIONS,
  ...NORTH_AMERICA_JURISDICTIONS,
  ...ASIA_PACIFIC_JURISDICTIONS,
  ...AFRICA_JURISDICTIONS,
];

// Helper functions
export function getJurisdictionByCode(code: string): JurisdictionConfig | undefined {
  return ALL_JURISDICTIONS.find(j => j.code === code);
}

export function getJurisdictionsByRegion(region: string): JurisdictionConfig[] {
  return ALL_JURISDICTIONS.filter(j => j.region === region);
}

export function getFilingRequirement(jurisdictionCode: string, filingId: string): FilingRequirement | undefined {
  const jurisdiction = getJurisdictionByCode(jurisdictionCode);
  return jurisdiction?.filingRequirements.find(f => f.id === filingId);
}

export function getUpcomingFilings(jurisdictionCode: string, days: number = 90): FilingRequirement[] {
  const jurisdiction = getJurisdictionByCode(jurisdictionCode);
  if (!jurisdiction) return [];

  const now = new Date();
  const futureDate = new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

  return jurisdiction.filingRequirements.filter(filing => {
    const dueDate = getNextDueDate(filing);
    return dueDate >= now && dueDate <= futureDate;
  });
}

export function getNextDueDate(filing: FilingRequirement): Date {
  const now = new Date();
  const year = now.getFullYear();
  
  let dueDate: Date;
  
  if (filing.type === 'ANNUAL' && filing.dueMonth) {
    dueDate = new Date(year, filing.dueMonth - 1, filing.dueDay);
    if (dueDate < now) {
      dueDate = new Date(year + 1, filing.dueMonth - 1, filing.dueDay);
    }
  } else if (filing.type === 'QUARTERLY') {
    const currentQuarter = Math.floor(now.getMonth() / 3);
    const quarterEndMonth = (currentQuarter + 1) * 3;
    dueDate = new Date(year, quarterEndMonth, filing.dueDay);
    if (dueDate < now) {
      const nextQuarterEndMonth = ((currentQuarter + 1) % 4 + 1) * 3;
      dueDate = new Date(nextQuarterEndMonth < quarterEndMonth ? year + 1 : year, nextQuarterEndMonth, filing.dueDay);
    }
  } else {
    dueDate = new Date(year, now.getMonth() + 1, filing.dueDay);
    if (dueDate < now) {
      dueDate = new Date(year, now.getMonth() + 2, filing.dueDay);
    }
  }
  
  return dueDate;
}

export function getDaysUntilDue(filing: FilingRequirement): number {
  const dueDate = getNextDueDate(filing);
  const now = new Date();
  return Math.ceil((dueDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}

export function isFilingOverdue(filing: FilingRequirement, submittedDate?: Date): boolean {
  if (submittedDate) return false;
  return getDaysUntilDue(filing) < 0;
}

export function getComplianceRiskLevel(jurisdictionCode: string, metrics: {
  solvencyMargin: number;
  capitalRatio: number;
  equityPercent: number;
  singleIssuerPercent: number;
}): 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL' {
  const jurisdiction = getJurisdictionByCode(jurisdictionCode);
  if (!jurisdiction) return 'HIGH';

  let riskScore = 0;

  // Check solvency margin
  if (metrics.solvencyMargin < jurisdiction.capitalRequirements.solvencyMarginPercent * 0.8) {
    riskScore += 3;
  } else if (metrics.solvencyMargin < jurisdiction.capitalRequirements.solvencyMarginPercent) {
    riskScore += 1;
  }

  // Check capital ratio
  if (metrics.capitalRatio < jurisdiction.capitalRequirements.capitalAdequacyRatio * 0.8) {
    riskScore += 3;
  } else if (metrics.capitalRatio < jurisdiction.capitalRequirements.capitalAdequacyRatio) {
    riskScore += 1;
  }

  // Check investment limits
  if (metrics.equityPercent > jurisdiction.investmentLimits.maxEquityPercent) {
    riskScore += 2;
  }
  if (metrics.singleIssuerPercent > jurisdiction.investmentLimits.maxSingleIssuerPercent) {
    riskScore += 2;
  }

  if (riskScore >= 6) return 'CRITICAL';
  if (riskScore >= 4) return 'HIGH';
  if (riskScore >= 2) return 'MEDIUM';
  return 'LOW';
}

// Export region list for UI
export const REGIONS = [
  { id: 'Caribbean', name: 'Caribbean', jurisdictionCount: CARIBBEAN_JURISDICTIONS.length },
  { id: 'Latin America', name: 'Latin America', jurisdictionCount: LATIN_AMERICA_JURISDICTIONS.length },
  { id: 'Europe', name: 'Europe', jurisdictionCount: EUROPE_JURISDICTIONS.length },
  { id: 'North America', name: 'North America', jurisdictionCount: NORTH_AMERICA_JURISDICTIONS.length },
  { id: 'Asia-Pacific', name: 'Asia-Pacific', jurisdictionCount: ASIA_PACIFIC_JURISDICTIONS.length },
  { id: 'Africa', name: 'Africa', jurisdictionCount: AFRICA_JURISDICTIONS.length },
];
